import { randomUUID } from 'node:crypto'
import { resolve } from 'node:path'
import { expect, test } from '@playwright/test'

test('owner registers an empty organization, uploads a PDF and runs the real pipeline through the UI', async ({ page }, testInfo) => {
  test.setTimeout(150000)
  const email = `owner-${randomUUID()}@example.invalid`
  const password = 'Fictitious owner password 2026!'
  const supplierName = 'Horizonte Documental · fictício'
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/login')
  await page.getByRole('button', { name: 'Criar conta', exact: true }).click()
  await expect(page.getByRole('form', { name: 'Cadastro de conta' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('owner-registration-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('owner-registration-mobile.png'), fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByLabel('Seu nome').fill('Ana Owner · QA fictícia')
  await page.getByLabel('Nome da organização').fill('Atlas Inicial · QA fictícia')
  await page.getByLabel('E-mail institucional').fill(email.toUpperCase())
  await page.getByLabel('Senha corporativa').fill(password)
  await page.getByLabel('Confirmar senha').fill(password)
  const registered = page.waitForResponse(response => response.url().endsWith('/api/v1/register') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Criar conta e acessar' }).click()
  expect((await registered).status()).toBe(201)
  await expect(page.getByRole('heading', { name: 'Visão geral', exact: true })).toBeVisible()
  const identity = await (await page.request.get('/api/v1/me')).json()
  expect(identity.data).toMatchObject({ role: 'owner', demo: null, user: { email } })
  expect(identity.data.permissions).toContain('analysis.run')
  expect((await (await page.request.get('/api/v1/suppliers')).json()).data).toEqual([])
  expect((await (await page.request.get('/api/v1/requirement-sets')).json()).data).toEqual([])

  // Every visible main-navigation destination must have a real, loaded page.
  const nav = page.getByRole('navigation', { name: 'Principal', exact: true })
  expect(await nav.getByRole('link').allTextContents()).not.toContain('Análises')
  expect(await nav.getByRole('link').allTextContents()).not.toContain('Revisões')
  for (const [label, heading] of [
    ['Requisitos', 'Conjuntos de Requisitos'], ['Comparações', 'Comparação de fornecedores'],
    ['Auditoria', 'Trilha de auditoria'], ['Central de Ajuda', 'Central de Ajuda'],
    ['Visão Geral', 'Visão geral'], ['Fornecedores', 'Gestão de Fornecedores'],
  ]) {
    await nav.getByRole('link', { name: label!, exact: true }).click()
    await expect(page.locator('#main-content h1')).toHaveText(heading!)
    await expect(page.getByText(/área está sendo preparada/i)).toHaveCount(0)
    await expect(page.locator('.resource-skeleton')).toHaveCount(0)
    await expect(page.getByRole('alert')).toHaveCount(0)
  }
  await expect(page.getByText('Nenhum fornecedor cadastrado', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Novo fornecedor' }).click()
  await page.getByLabel('Razão social').fill(supplierName)
  await page.getByRole('button', { name: 'Salvar fornecedor', exact: true }).click()
  await page.getByRole('link', { name: supplierName, exact: true }).click()
  await expect(page.getByRole('heading', { name: supplierName, exact: true })).toBeVisible()
  const supplierPath = new URL(page.url()).pathname
  await expect(page.getByText(/nenhuma versão publicada/i)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Iniciar análise documental' })).toBeDisabled()
  await page.getByRole('link', { name: 'Criar e publicar conjunto' }).click()
  await page.getByRole('button', { name: 'Novo conjunto', exact: true }).click()
  await page.getByLabel('Nome do conjunto').fill('Homologação inicial')
  await page.getByLabel('Código 1', { exact: true }).fill('OWNER-01')
  await page.getByLabel('Título 1', { exact: true }).fill('Política de privacidade')
  await page.getByLabel('Categoria 1', { exact: true }).fill('Privacidade')
  await page.getByLabel('Critério de avaliação 1').fill('Localize a finalidade e o acesso ao tratamento de dados pessoais na política de privacidade.')
  await page.getByRole('button', { name: 'Salvar rascunho', exact: true }).click()
  await page.getByRole('button', { name: 'Publicar versão', exact: true }).click()
  const publication = page.waitForResponse(response => response.url().endsWith('/publish') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Confirmar publicação', exact: true }).click()
  const published = await publication
  expect(published.status()).toBe(200)
  const setId = (await published.json()).data.id
  await expect(page.getByRole('status')).toContainText('Versão publicada')
  await nav.getByRole('link', { name: 'Fornecedores', exact: true }).click()
  await page.getByRole('link', { name: supplierName, exact: true }).click()
  await page.getByRole('link', { name: 'Enviar documentos PDF', exact: true }).click()
  await page.getByLabel('Arquivos PDF').setInputFiles(resolve('../demo-assets/politica-privacidade-ficticia.pdf'))
  const uploaded = page.waitForResponse(response => response.url().includes('/documents') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Confirmar e enviar PDF' }).click()
  const upload = await uploaded
  expect(upload.status()).toBe(201)
  const document = (await upload.json()).data
  expect(document.status).toBe('uploaded')
  await expect(page.getByRole('status')).toContainText('PDF recebido com sucesso')
  await page.getByRole('link', { name: 'Voltar ao dossiê' }).click()
  const form = page.getByRole('form', { name: 'Iniciar análise documental' })
  await form.getByLabel('Conjunto de requisitos').selectOption(setId)
  await form.getByRole('checkbox').check()
  await expect(form.getByRole('button', { name: 'Iniciar análise documental' })).toBeEnabled()
  await page.screenshot({ path: testInfo.outputPath('owner-analysis-selection-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('owner-analysis-selection-mobile.png'), fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  const started = page.waitForResponse(response => response.url().endsWith('/analyses') && response.request().method() === 'POST')
  await form.getByRole('button', { name: 'Iniciar análise documental' }).click()
  const start = await started
  expect(start.status()).toBe(202)
  expect(start.request().headers()['idempotency-key']).toMatch(/^analysis-ui:[0-9a-f-]{36}$/)
  expect(start.request().postDataJSON()).toEqual({ requirement_set_id: setId, document_ids: [document.id] })
  const runId = (await start.json()).data.id
  await expect(page).toHaveURL(new RegExp(`/analises/${runId}$`))
  // Only the real database worker and HMAC-authenticated FastAPI can produce this result.
  await expect(page.getByRole('heading', { name: 'Análise concluída', exact: true })).toBeVisible({ timeout: 70000 })
  const completed = (await (await page.request.get(`/api/v1/analyses/${runId}`)).json()).data
  expect(completed).toMatchObject({ status: 'completed', progress: 100, attempts: 1 })
  await page.screenshot({ path: testInfo.outputPath('owner-analysis-completed.png'), fullPage: true })
  await page.getByRole('link', { name: 'Matriz de conformidade' }).click()
  await page.getByRole('button', { name: 'Inspecionar OWNER-01', exact: true }).click()
  const evidence = page.getByRole('dialog')
  await expect(evidence.getByText(document.id, { exact: true })).toBeVisible()
  await expect(evidence.getByText(/Página 1/)).toBeVisible()
  await expect(evidence.locator('blockquote')).toContainText('dados pessoais')
  await page.screenshot({ path: testInfo.outputPath('owner-evidence.png') })
  await evidence.getByLabel('Justificativa humana', { exact: true }).fill('Inspeção humana do PDF fictício e de suas limitações.')
  await evidence.getByRole('checkbox').check()
  await evidence.getByRole('button', { name: 'Salvar revisão' }).click()
  await expect(evidence.getByRole('status')).toContainText('Revisão registrada')
  await evidence.getByRole('button', { name: 'Fechar evidência' }).click()
  await page.getByRole('combobox', { name: 'Decisão final humana', exact: true }).selectOption('conditional')
  await page.getByLabel('Justificativa da decisão').fill('Decisão fictícia condicionada à verificação humana dos documentos reais.')
  await page.getByRole('checkbox', { name: /assumo a responsabilidade/i }).check()
  await page.getByRole('button', { name: 'Registrar decisão humana', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Decisão humana registrada · imutável', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Inspecionar OWNER-01', exact: true })).toBeVisible()
  await expect(page.getByText('Condicionado por decisão humana', { exact: true })).toBeVisible()
  // A completed decision preserves the earlier record and still allows an explicit new run.
  await page.goto(supplierPath)
  const secondForm = page.getByRole('form', { name: 'Iniciar análise documental' })
  await secondForm.getByLabel('Conjunto de requisitos').selectOption(setId)
  await secondForm.getByRole('checkbox').check()
  const restarted = page.waitForResponse(response => response.url().endsWith('/analyses') && response.request().method() === 'POST')
  await secondForm.getByRole('button', { name: 'Iniciar análise documental' }).click()
  const restart = await restarted
  expect(restart.status()).toBe(202)
  expect(restart.request().headers()['idempotency-key']).not.toBe(start.request().headers()['idempotency-key'])
  const nextRunId = (await restart.json()).data.id
  expect(nextRunId).not.toBe(runId)
  await expect(page).toHaveURL(new RegExp(`/analises/${nextRunId}$`))
  await expect(page.getByRole('heading', { name: 'Análise concluída', exact: true })).toBeVisible({ timeout: 70000 })
  await page.getByRole('button', { name: 'Sair da conta' }).click()
  await expect(page.getByRole('form', { name: 'Acesso à plataforma' })).toBeVisible()
  expect((await page.request.get('/api/v1/me', { headers: { Accept: 'application/json' } })).status()).toBe(401)
  await page.getByLabel('E-mail institucional').fill(email.toUpperCase())
  await page.getByLabel('Senha corporativa').fill(password)
  await page.getByRole('button', { name: 'Entrar na Plataforma' }).click()
  await expect(page.getByRole('heading', { name: 'Visão geral', exact: true })).toBeVisible()
  await page.reload()
  const restored = (await (await page.request.get('/api/v1/me')).json()).data
  expect(restored.user.id).toBe(identity.data.user.id)
  expect(restored.organization.id).toBe(identity.data.organization.id)
  await page.goto(supplierPath)
  await expect(page.getByRole('link', { name: 'Matriz de conformidade' })).toBeVisible()
  await expect(page.getByRole('form', { name: 'Iniciar análise documental' })).toBeVisible()
  await expect(page.getByRole('checkbox')).toHaveAccessibleName(/Processado.*disponível para nova análise/)
  expect(errors).toEqual([])
})
