import type { FindingStatus, FindingReview } from './domain'
export interface DashboardMetrics { suppliers_analyzed: number; requirements_met: number; pending_requirements: number; analyses_awaiting_review: number }
export interface ComparisonCell { finding_id: string; ai: { status: FindingStatus; justification: string; confidence: number; search_summary: string | null }; human_review: Omit<FindingReview, 'finding_id'> | null; requires_human_review: boolean; evidence: { id: string; document_id: string; page_number: number; quote: string; quote_truncated: boolean; start_offset: number; end_offset: number }[]; evidence_total: number }
export interface ComparisonSide { supplier: { id: string; name: string }; analysis: { id: string; completed_at: string | null; is_latest_for_supplier: boolean } | null }
export interface Comparison { requirement_set: { id: string; name: string; version: number; is_current: boolean }; left: ComparisonSide; right: ComparisonSide; rows: { requirement: { id: string; code: string; title: string; category: string; position: number; is_required: boolean }; left: ComparisonCell | null; right: ComparisonCell | null }[] }
export interface HumanDecision { id: string; decision: 'approved' | 'rejected' | 'conditional'; reason: string; decided_at: string }
export interface DecisionContext { analysis_id: string; supplier_id: string | null; requirement_set_id: string | null; status: string; required_pending: number; is_latest_for_supplier: boolean; is_current_checklist: boolean; decision: HumanDecision | null }
export interface AuditEvent { id: string; organization_public_id: string | null; actor_public_id: string | null; action: string; target_type: string; target_id: string | null; metadata: Record<string, unknown> | null; previous_hash: string | null; event_hash: string | null; occurred_at: string }
export interface AuditPage { data: AuditEvent[]; meta: { current_page: number; last_page: number; per_page: number; total: number; integrity: { status: 'verified' | 'broken' | 'empty' | 'unverifiable'; scope: 'page' } } }
